apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: workshop
  resourceVersion: "4"
spec:
  selector:
    matchLabels:
      fleet: "workshop"
  template:
    metadata:
      labels:
        fleet: workshop
    spec:
      applications:
      - envVars:
          IMAGE_NAME: quay.io/luisarizmendi/modelcar-hardhat:v1
        image: quay.io/luisarizmendi/compose-triton:latest
        name: triton
      config:
      - name: motd-update
        configType: InlineConfigProviderSpec
        inline:
          - path: "/etc/motd"
            content: "This system is managed by flightctl."
            mode: 0644
      - gitRef:
          mountPath: /
          path: /configs/site/{{ .metadata.labels.site }}
          repository: user01-fleet-mgmt
          targetRevision: main
        name: site-config
      - gitRef:
          mountPath: /
          path: /configs/function/{{ .metadata.labels.function }}
          repository: user01-fleet-mgmt
          targetRevision: main
        name: function-config
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
      os:
        image: workshop-registry-quay-openshift-operators.apps.cluster-bndlv.bndlv.sandbox2791.opentlc.com/user01/type-1:prod



