FROM registry.redhat.io/rhel10/rhel-bootc:10.0

## Install core packages
RUN dnf -y --nogpgcheck install curl jq && dnf clean all

## Install additional packages
#RUN dnf -y --nogpgcheck install tmux  && dnf clean all




