FROM registry.redhat.io/rhel10/rhel-bootc:10.0

## Enable subscription
RUN rm -rf /etc/rhsm-host
RUN subscription-manager register --username $REDHAT_USERNAME --password $REDHAT_PASSWORD

## Install packages
#RUN dnf -y update
RUN dnf -y install tmux && dnf clean all

## Clean-up
RUN subscription-manager unregister && subscription-manager clean && insights-client --unregister
RUN ln -s /run/secrets/rhsm /etc/rhsm-host
