kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: object-detection-crb
subjects:
  - kind: ServiceAccount
    name: object-sa
    namespace: object-detection
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

