FROM quay.io/openshift/origin-cli:latest

ENV HELM_VERSION="v3.13.2"

ENV ARCH="amd64"

USER root

WORKDIR /opt/app-root/src


RUN dnf install -y tar gzip && \
    curl -fsSL -o /tmp/helm.tar.gz "https://get.helm.sh/helm-${HELM_VERSION}-linux-${ARCH}.tar.gz" && \
    tar -zxvf /tmp/helm.tar.gz -C /tmp && \
    mv /tmp/linux-${ARCH}/helm /usr/local/bin/helm && \
    chmod +x /usr/local/bin/helm && \
    rm -rf /tmp/helm.tar.gz /tmp/linux-${ARCH} && \
    dnf clean all


USER 1001

ENTRYPOINT ["helm"]

