
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-showroom
  namespace: openshift-gitops
spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      containers:
      - name: bootstrap-showroom
        image: quay.io/luisarizmendi/helm-cli:latest  
        command: ["/bin/sh", "-c"]
        args:
        - |
          export HOME=/tmp  # Fix permission issues

          NAMESPACE="showroom"

          echo "Creating values.yaml..."
          cat <<EOF > /tmp/values.yaml
          # Common
          git-workshop-url: https://github.com/luisarizmendi/workshop-moving-ai-to-the-edge
          openshift-console: https://console-openshift-console.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com/
          openshift-api: https://api.cluster-np6lk.np6lk.sandbox2077.opentlc.com:6443
          openshift-user-base: user
          openshift-password-base: redhat
          gitea-server: gitea.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com
          container-registry-gitea: 192.168.1.100
          container-registry-gitea-user: gitea
          container-registry-gitea-pass: gitea
          shared-nvidia-ip: 192.168.1.2
          shared-nvidia-user: admin
          shared-nvidia-pass: R3dh4t1!
          gateway-dns-dhcp-openwrt: http://192.168.1.1
          # Platform
          device-ip-base: 192.168.100.1
          device-username: admin
          device-password: secret
          openshift-ai: https://rhods-dashboard-redhat-ods-applications.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com/
          flightctl-ui: https://flightui-flightctl.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com/
          flightctl-api: https://flightapi-flightctl.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com/
          flightctl-user-basename: flightctluser
          flightctl-password: secretflightctl
          registry-local-url: http://192.168.100.200/workshop/
          # AI
          minio-ui: https://minio-ui-minio.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com
          minio-api: https://minio-api-minio.apps.cluster-np6lk.np6lk.sandbox2077.opentlc.com
          minio-user-base: user
          minio-password-base: redhat
          registry-url: https://quay.io/user/luisarizmendi/
          EOF

          echo "Ensuring the project exists..."
          if ! /usr/bin/oc get project $NAMESPACE >/dev/null 2>&1; then
            /usr/bin/oc new-project $NAMESPACE
          fi

          echo "Fetching cluster domain..."
          clusterdomain_apps=$(/usr/bin/oc get ingresses.config.openshift.io cluster -o jsonpath='{.spec.domain}')

          echo "Running Helm template..."
          helm repo add larizmen-charts https://raw.githubusercontent.com/luisarizmendi/helm-chart-repo/main/packages
          helm repo update

          helm template showroom larizmen-charts/showroom-single-pod --namespace=${NAMESPACE}  \
          --set deployer.domain=${clusterdomain_apps} \
          --set-file content.user_data=/tmp/values.yaml \
          --set content.repoUrl=https://github.com/luisarizmendi/workshop-moving-ai-to-the-edge \
          --set general.guid=1 \
          --set-string content.contentOnly="true" \
          | /usr/bin/oc apply -f -

          echo "Environment ready!"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Never
  backoffLimit: 1


