[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    '''deployment\/openshift\/bootstrap-lab\/manifests\/common\/00-users-pass.yaml''',

        
