FROM registry.access.redhat.com/ubi9:latest 

USER root

RUN dnf install -y \
    python3 python3-pip\
    && dnf clean all \
    && python3 -m ensurepip --upgrade
    
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install --no-cache-dir s3cmd

WORKDIR /opt/app-root/src

USER 1001

CMD ["s3cmd"]
