apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-server
  template:
    metadata:
      labels:
        app: inference-server
    spec:
      containers:
        - name: inference-server
          image: quay.io/luisarizmendi/object-detection-inference-server:prod
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: 1 
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-server
spec:
  selector:
    app: inference-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inference-server
  labels:
    app: inference-server
spec:
  to:
    kind: Service
    name: inference-server
  port:
    targetPort: 8080