kind: Deployment
apiVersion: apps/v1
metadata:
  name: hardhat-inference
  labels:
    app: hardhat-inference
spec:
  selector:
    matchLabels:
      app: hardhat-inference
  replicas: 1
  template:
    metadata:
      labels:
        app: hardhat-inference
    spec:
      restartPolicy: Always
      initContainers:
        - name: model-downloader
          image: quay.io/skopeo/stable
          command:
            - /bin/sh
            - -c
            - |
              set -ex
              mkdir -p /mnt/models
              skopeo copy --override-os linux docker://quay.io/luisarizmendi/modelcar-hardhat-or-hat:onnx oci-archive:/tmp/modelcar.tar
              mkdir -p /tmp/image
              tar -xf /tmp/modelcar.tar -C /tmp/image
              for layer in /tmp/image/blobs/sha256/*; do
                tar -tf "$layer" | grep '^models/' && tar -xf "$layer" -C /mnt/models --strip-components=1 || true
              done
              rm -rf /tmp/modelcar.tar /tmp/image
          volumeMounts:
            - name: model-storage
              mountPath: /mnt/models
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              httpGet:
                path: /wait-for-drain
                port: 8022
                scheme: HTTP
          name: inference-container
          ports:
            - name: user-port
              containerPort: 8888
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: model-storage
              mountPath: /mnt/models
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/modh/openvino_model_server@sha256:e4ece481b8dd866163da7ffcd3e95389ef7fb3d32a9a0dbb056b07839652a4f7'
          args:
            - '--model_name=hardhat'
            - '--port=8001'
            - '--rest_port=8888'
            - '--model_path=/mnt/models'
            - '--file_system_poll_wait_seconds=0'
            - '--grpc_bind_address=0.0.0.0'
            - '--rest_bind_address=0.0.0.0'
            - '--target_device=AUTO'
            - '--metrics_enable'
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 2Gi
        - name: model-storage
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%

