apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-detection
  name: object-detection-inference-server-service
  namespace: object-detection
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: object-detection-inference-server
  type: LoadBalancer

