apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-detection
  name: object-detection-stream-manager-service
  namespace: object-detection
spec:
  ports:
  - name: "5000"
    nodePort: 32160
    port: 5000
    targetPort: 5000
  selector:
    app: object-detection-stream-manager
  type: NodePort

