FROM registry.redhat.io/rhel10/rhel-bootc:10.0

## Install base packages
RUN dnf -y --nogpgcheck install tmux  && dnf clean all

## Enable RHEM
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install flightctl-agent && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer
ADD config.yaml /etc/flightctl/

