FROM registry.redhat.io/rhel10/rhel-bootc:10.0

## Enable subscription
RUN if [ -f /run/secrets/username ] && [ -f /run/secrets/password ]; then \
    rm -rf /etc/rhsm-host && \
    RHUSER=$(cat /run/secrets/username) && \
    RHPASS=$(cat /run/secrets/password) && \
    echo "Registering with Red Hat subscription manager..." && \
    subscription-manager register --username "$RHUSER" --password "$RHPASS"; \
    else \
        echo "Red Hat credentials not found; skipping subscription registration."; \
    fi

## Install additional packages
RUN dnf -y --nogpgcheck install tmux && dnf clean all

## Clean-up


RUN if [ -f /run/secrets/username ] && [ -f /run/secrets/password ]; then \
RHUSER=$(cat /run/secrets/username) && \
RHPASS=$(cat /run/secrets/password) && \
HOSTNAME=$(hostname -f) && \
echo "Unregistering system $HOSTNAME from Red Hat Cloud inventory..." && \
for HOST_ID in $(curl -s -u "$RHUSER:$RHPASS" "https://cloud.redhat.com/api/inventory/v1/hosts?fqdn=$HOSTNAME" | grep -o '"id":"[^"]*' | grep -o '[^"]*$'); do \
  curl -s -u "$RHUSER:$RHPASS" -X DELETE "https://cloud.redhat.com/api/inventory/v1/hosts/$HOST_ID" -H "accept: */*"; \
done && \
subscription-manager unregister && subscription-manager clean && \
ln -s /run/secrets/rhsm /etc/rhsm-host; \
else \
echo "Red Hat credentials not found; skipping subscription clean-up."; \
fi