apiVersion: v1
kind: ConfigMap
metadata:
  name: group-config
data:
  groups.json: |
    {
      "Group 01": { "url": "https://showroom-user01-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 02": { "url": "https://showroom-user02-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 03": { "url": "https://showroom-user03-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 04": { "url": "https://showroom-user04-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 05": { "url": "https://showroom-user05-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 06": { "url": "https://showroom-user06-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 07": { "url": "https://showroom-user07-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 08": { "url": "https://showroom-user08-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 09": { "url": "https://showroom-user09-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 10": { "url": "https://showroom-user10-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 11": { "url": "https://showroom-user11-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 12": { "url": "https://showroom-user12-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 13": { "url": "https://showroom-user13-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 14": { "url": "https://showroom-user14-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 15": { "url": "https://showroom-user15-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 16": { "url": "https://showroom-user16-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 17": { "url": "https://showroom-user17-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 18": { "url": "https://showroom-user18-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 19": { "url": "https://showroom-user19-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 20": { "url": "https://showroom-user20-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 21": { "url": "https://showroom-user21-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 22": { "url": "https://showroom-user22-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 23": { "url": "https://showroom-user23-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 24": { "url": "https://showroom-user24-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 25": { "url": "https://showroom-user25-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 26": { "url": "https://showroom-user26-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 27": { "url": "https://showroom-user27-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 28": { "url": "https://showroom-user28-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 29": { "url": "https://showroom-user29-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 30": { "url": "https://showroom-user30-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 31": { "url": "https://showroom-user31-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 32": { "url": "https://showroom-user32-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 33": { "url": "https://showroom-user33-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 34": { "url": "https://showroom-user34-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 35": { "url": "https://showroom-user35-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 36": { "url": "https://showroom-user36-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 37": { "url": "https://showroom-user37-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 38": { "url": "https://showroom-user38-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 39": { "url": "https://showroom-user39-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 40": { "url": "https://showroom-user40-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 41": { "url": "https://showroom-user41-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 42": { "url": "https://showroom-user42-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 43": { "url": "https://showroom-user43-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 44": { "url": "https://showroom-user44-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 45": { "url": "https://showroom-user45-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 46": { "url": "https://showroom-user46-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 47": { "url": "https://showroom-user47-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 48": { "url": "https://showroom-user48-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 49": { "url": "https://showroom-user49-workshop-guide.apps.<cluster-domain>/", "info": "" },
      "Group 50": { "url": "https://showroom-user50-workshop-guide.apps.<cluster-domain>/", "info": "" }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-group-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-group-selector
  template:
    metadata:
      labels:
        app: workshop-group-selector
    spec:
      containers:
      - name: workshop-group-selector
        image: quay.io/luisarizmendi/workshop-group-selector:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: group-config
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-group-selector-service
spec:
  selector:
    app: workshop-group-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: workshop-group-selector-route
  labels:
    app: workshop-group-selector
spec:
  to:
    kind: Service
    name: workshop-group-selector
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
